#!/usr/bin/python3
from sys import argv
from math import sqrt


def factor():
    with open(argv[1]) as file:
        for line in file:
            num = int(line)
            if num % 2 == 0:
                print("{:d}={}*2".format(num, num//2))
                continue
            sqn = int(sqrt(num))
            if sqn % 2 == 0:
                sqn += 1
            for i in range(3, sqn + 1, 2):
                if num % i == 0:
                    print("{:d}={}*{}".format(num, i, num//i))
                    break
            if num % i != 0:
                print("{}={}*1".format(num, num))


factor()
